---
title: "EDA"
author: "Lewis Luttrell"
date: "10/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(mosaic)
```

```{r}
Ames <- read_csv("Ames.csv")
```

```{r}
favstats(~Lot_Area, data = Ames, na.rm=TRUE)
```


```{r}
histogram(~Lot_Area, data = Ames, type="count", breaks=seq(1200, 222000, 2500))
```

```{r}
xyplot(SalePrice~Lot_Area, data = Ames, pch=19)
```

```{r}
cor(SalePrice~Lot_Area, data = Ames)
```


```{r}
favstats(~Bedroom_AbvGr, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~Bedroom_AbvGr, data = Ames, type="count", breaks=seq(0, 9, 1))
```

```{r}
xyplot(SalePrice~Bedroom_AbvGr, data = Ames, pch=19)
```

```{r}
cor(SalePrice~Bedroom_AbvGr, data = Ames, use="complete.obs")
```


```{r}
Ames <- Ames %>% mutate(Half_Bath = Half_Bath * .5)
Ames <- Ames %>% mutate(Bsmt_Half_Bath = Bsmt_Half_Bath * .5)
Ames <- Ames %>% mutate(TotalBath = Full_Bath + Half_Bath + Bsmt_Full_Bath + Bsmt_Half_Bath)
```

```{r}
favstats(~TotalBath, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~TotalBath, data = Ames, type = "count", breaks = seq(0, 9, 1))
```

```{r}
xyplot(SalePrice~TotalBath, data = Ames, pch=19)
```

```{r}
cor(SalePrice~TotalBath, data = Ames, use="complete.obs")
```


```{r}
favstats(~Total_Bsmt_SF, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~Total_Bsmt_SF, data = Ames, type="count", breaks = seq(0, 6500, 500))
```

```{r}
xyplot(SalePrice~Total_Bsmt_SF, data = Ames, pch=19)
```

```{r}
cor(SalePrice~Total_Bsmt_SF, data = Ames, use="complete.obs")
```


```{r}
favstats(~Garage_Area, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~Garage_Area, data = Ames, type = "count", breaks = seq(0, 1500, 100))
```

```{r}
xyplot(SalePrice~Garage_Area, data = Ames, pch=19)
```

```{r}
cor(SalePrice~Garage_Area, data = Ames, use="complete.obs")
```


```{r}
favstats(~Year_Built, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~Year_Built, data = Ames, type = "count", breaks = seq(1870, 2012, 10))
```

```{r}
xyplot(SalePrice~Year_Built, data = Ames, pch=19)
```

```{r}
cor(SalePrice~Year_Built, data = Ames, use = "complete.obs")
```


```{r}
Ames <- Ames %>% 
  mutate(TotalSqFt = SF_1st_Flr + SF_2nd_Flr)
```

```{r}
favstats(~TotalSqFt, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~TotalSqFt, data = Ames, type = "count", breaks = seq(200, 5750, 250))
```

```{r}
xyplot(SalePrice~TotalSqFt, data = Ames, pch=19)
```

```{r}
cor(SalePrice~TotalSqFt, data = Ames)
```


```{r}
Ames <- Ames %>% 
  mutate(OvrCondQual = Overall_Cond + Overall_Qual)
```

```{r}
favstats(~OvrCondQual, data = Ames, na.rm = TRUE)
```

```{r}
histogram(~OvrCondQual, data = Ames, type = "count", breaks = seq(0, 20, 1))
```

```{r}
xyplot(SalePrice~OvrCondQual, data = Ames, pch=19)
```

```{r}
cor(SalePrice~OvrCondQual, data = Ames)
```

```{r}
Ames <- Ames %>% 
  mutate(Year_Built_Cond = Year_Built * Overall_Cond)
```

```{r}
Ames <- Ames %>% 
  mutate(Total_SF_Bsmt_SF = TotalSqFt * Total_Bsmt_SF)
```

```{r}
Ames <- Ames %>% 
  mutate(CA.yes = ifelse(Central_Air == 'Y', 1, 0))
```

```{r}
Ames <- Ames %>% 
  mutate(Garage.no = ifelse(Garage_Type == 'NA', 1, 0))
```

```{r}
Ames <- Ames %>% 
  rename(Y = SalePrice, X1 = Lot_Area, X2 = Bedroom_AbvGr, X3 = TotalBath, X4 = Total_Bsmt_SF, x5 = Garage_Area, X6 = Year_Built, X7 = TotalSqFt, X8 = OvrCondQual, X9 = Garage_Type, X10 = Central_Air, X11 = Year_Built_Cond, X12 = Total_SF_Bsmt_SF)
```


